<ns2:SendRequestRequest xmlns:ns3="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1" xmlns:ns2="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1" xmlns="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1">
    <ns:SenderProvidedRequestData Id="SIGNED_BY_CONSUMER" xmlns="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1" xmlns:ns="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1" xmlns:ns2="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1">
        <ns:MessageID>#MESSAGE_ID#</ns:MessageID>
        <ns2:MessagePrimaryContent>#REQUEST_BODY#</ns2:MessagePrimaryContent>
    </ns:SenderProvidedRequestData>
    <ns2:CallerInformationSystemSignature></ns2:CallerInformationSystemSignature>
</ns2:SendRequestRequest>